filebeat:
  registry_file: /tmp/filebeat/registry
  prospectors:
    - paths:
        - /usr/local/jss/logs/JAMFChangeManagement.log
      input_type: log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      fields:
        jamf_instance:
          host: jamf.instance.host
    - paths:
        - /usr/local/jss/logs/JAMFSoftwareServer.log
      input_type: log
      multiline:
        pattern: '^2'
        negate: true
        match: after
      fields:
        jamf_instance:
          host: jamf.instance.host
    - paths:
        - /usr/local/jss/logs/JSSAccess.log
      input_type: log
      fields:
        jamf_instance:
          host: jamf-pro.apfelwerk.io

output:
  logstash:
    hosts:
      - "zentral:5044"
    ssl:
      certificate_authorities:
        - "/path/to/zentral_fullchain.crt"

logging:
  level: info
  to_files: true
  to_syslog: false
  files:
    path: /tmp/filebeat
    name: jamf_logs
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 7
